### ISSUE TITLE
Usprawnienia pobierania dużych obszarów

### ISSUE THREAD

**Issue by Tailwhip** [envirosolutionspl/pobieracz_danych_gugik#10]
Witam,

używam wtyczki do pobierania dużych obszarów, rzędu powiatów, a nawet województw. 
Wtyczka jest w stanie poprawnie pobrać takie obszary jednak, brakuje jej kilku przydatnych funkcji, które wspomagały by takie pobieranie, np:
- obsługa timeoutów pobierania - pobieranie potrafi się zamrozić, a w przypadku pobierania np. 10 000 zdjęć jest to trochę kłopotliwe;
- pasek progresu procesu zbierania requestów - bo w tym momencie program się mrozi i użytkownik może pomyśleć, że tak już zostanie;
- funkcja wznawiania pobierania - w przypadku, gdy z jakiegoś powodu poprzednia sesja pobierania zostanie przerwana, to nie ma sensu pobierać ponownie tych samych zdjęć. Taka funkcja przydała by się również dla procesu zbierania requestów, bo to tak na prawdę trwa najdłużej.

Udało mi się zaimplementować takie rozwiązania na lokalnej kopii.
Dodałem też kilka komunikatów dla użytkownika, żeby było wiadomo co się dzieje.

Jeśli coś z moich implementacji wyda wam się użyteczne to z miłą chęcią się tym dzielę ([pobieracz_danych_gugik.zip](https://github.com/envirosolutionspl/pobieracz_danych_gugik/files/7579112/pobieracz_danych_gugik.zip)).
Myślę, że szczególnie ta obsługa timeoutów jest najistotniejsza, szczególnie, że to dosłownie 5 linijek.

A tak poza tym wtyczka jest świetna i bardzo ułatwia życie.
Wielkie dzięki za wtyczkę i pozdrawiam!

**Comment by ptatar0308** [comment]
Do rozpatrzenia w przyszłości
