### ISSUE TITLE
Wtyczka nie działa. Python error.

### ISSUE THREAD

**Issue by JuanBreva** [envirosolutionspl/pobieracz_danych_gugik#105]
Od kilka dni mam ten problem i nie mogę pobierać NMT:

> 2024-05-08T20:16:17     WARNING    Traceback (most recent call last):
>               File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 622, in nmt_fromLayer_btn_clicked
>               isEvrf2007=isEvrf2007) if isNmpt else nmt_api.getNmtListbyPoint1992(
>               File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/nmt_api.py", line 62, in getNmtListbyPoint1992
>               lista += createList(resp)
>               File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/nmt_api.py", line 83, in createList
>               nmt = Nmt(**params)
>              TypeError: __init__() got an unexpected keyword argument 'dt_pzgik'
![Captura de Pantalla 2024-05-08 a las 20 23 24](https://github.com/envirosolutionspl/pobieracz_danych_gugik/assets/17232551/e36d8c2e-ecf8-4c9f-940b-79287678b2c4)

**Comment by wojtek19022** [comment]
Dzień dobry, proszę o więcej informacji:
- używana wersja QGIS,
- wersja zainstalowanej wtyczki
- wersja używanego systemu operacyjnego
- opisanie toku który doprowadził do tej sytuacji

**Comment by lukaszprawdziwy** [comment]
Dzień dobry, 
mam podobny kłopot przy pobieraniu ortofotomap. Problem najpierw pojawił się przy pobieraniu warstwą wektorową a dzień później przy pobieraniu przez wskazanie punktu. 


Wersja QGIS: 3.32.3-Lima

Wersja wtyczki: 1.0.10

Windows: 11 Pro

komunikat błędu: 

2024-05-09T08:57:54     WARNING    Traceback (most recent call last):File "C:\Users/mikolajczyk/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\pobieracz_danych_gugik.py", line 492, in orto_fromLayer_btn_clicked
              subList = ortofoto_api.getOrtoListbyPoint1992(point=point)
              File "C:\Users/mikolajczyk/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\ortofoto_api.py", line 48, in getOrtoListbyPoint1992
              ortofotomapa = Ortofotomapa(**params)
             TypeError: __init__() got an unexpected keyword argument 'dt_pzgik'

**Comment by wojtek19022** [comment]
A z jakich okolic pobierane są dane? Czasami jest to wina powiatowych serwerów, które różnie potrafią działać

**Comment by lukaszprawdziwy** [comment]
zaraz na południe od Krakowa (842788, 5537063 EPSG:32633)

**Comment by wojtek19022** [comment]
Faktycznie, występuje tutaj pewien błąd. Na szczęście przygotowujemy się do aktualizacji Pobieracza i niedługo zostanie ten błąd załatany ;)

**Comment by lukaszprawdziwy** [comment]
świetnie!
czy wiadomo mniej więcej kiedy się spodziewac tej aktualizacji?

**Comment by wojtek19022** [comment]
Planujemy w okolicach połowy maja zakończyć prace nad aktualizacją :)

**Comment by lukaszprawdziwy** [comment]
dzięki, czekam z niecierpliwościa

**Comment by JuanBreva** [comment]
Cieszę się, że to będzie naprawione. W każdym razie, jeśli to pomoże, oto potrzebne dane:

> 
>     * używana wersja QGIS: 3.36.0-Maidenhead
> 
>     * wersja zainstalowanej wtyczki: 1.0.10
> 
>     * wersja używanego systemu operacyjnego: MacOS Monterey 12.7.4
> 
>     * opisanie toku który doprowadził do tej sytuacji: Dodałem zrzut ekranu do oryginalnego postu

**Comment by wojtek19022** [comment]
> Od kilka dni mam ten problem i nie mogę pobierać NMT:
> 
> > 2024-05-08T20:16:17     WARNING    Traceback (most recent call last):
> > File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 622, in nmt_fromLayer_btn_clicked
> > isEvrf2007=isEvrf2007) if isNmpt else nmt_api.getNmtListbyPoint1992(
> > File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/nmt_api.py", line 62, in getNmtListbyPoint1992
> > lista += createList(resp)
> > File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/nmt_api.py", line 83, in createList
> > nmt = Nmt(**params)
> > TypeError: **init**() got an unexpected keyword argument 'dt_pzgik'
> > ![Captura de Pantalla 2024-05-08 a las 20 23 24](https://private-user-images.githubusercontent.com/17232551/329352722-e36d8c2e-ecf8-4c9f-940b-79287678b2c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjcwMzEsIm5iZiI6MTcxNTMyNjczMSwicGF0aCI6Ii8xNzIzMjU1MS8zMjkzNTI3MjItZTM2ZDhjMmUtZWNmOC00YzlmLTk0MGItNzkyODc2NzhiMmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA3Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMGZlYjZmM2JlZGMxYTcyOWI0NjU5N2NhMzYyNGE2Mzk4YWVlN2RhN2VhNjU4ZjFmNmY4ODFjOTRlNzM3NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xo-JDtCFA7kk7UpZewpE_h6x3GHPfitmbSEGZRZ939A)

O, dziękuję. Wcześniej musiały być problemy z Githubem, bo nie załadował mi się zrzut ekranu. Teraz widzę interfejs wtyczki

**Comment by wojtek19022** [comment]
@JuanBreva , @lukaszprawdziwy w poniedziałek zrobiłem pierwsze zmiany co do pobierania danych z WMS:
- ortofotomapa
- NMT
- NMPT

w tygodniu zrobię jeszcze zmiany co do 4 innych produktów których tyczył się błąd

**Comment by lukaszprawdziwy** [comment]
dzięki,
czy poprawiona wersja jest już dostępna? qgis widzi wciąż 1.0.10.

**Comment by wojtek19022** [comment]
Jeszcze nie, na razie na githubie na branchu dev jest dostępna wersja 1.1.0 alpha wtyczki. W piątek pojawi się tam również naprawiony omawiany wątek, ponieważ tyczył się on łącznie aż 7 produktów

**Comment by wojtek19022** [comment]
na branchu dev znajduje się przedpremierowa wersja wtyczki z poprawionym błędem :)
