### ISSUE TITLE
NMT ASCII TBD

### ISSUE THREAD

**Issue by michkowalczuk** [envirosolutionspl/pobieracz_danych_gugik#12]
GUGiK dodał do skorowidzy pobierania danych NMT informacje o numerycznym modelu terenu w formacie ASCII_TBD. Dane te charakteryzują się dobrą dokładnością, przy niedużym rozmiarze w porównaniu do XYZ, dzięki zastosowaniu obiektów liniowych i poligonowych.
Proponuję dodać możliwość pobierania tych danych za pomocą wtyczki.
Więcej o danych tu:
http://www.gugik.gov.pl/pzgik/zamow-dane/dane-pomiarowe

**Comment by ptatar0308** [comment]
W obecnej chwili nie znaleziono takich danych. Będą dodane takie dane, jeśli zostaną udostępnione przez GUGiK
