### ISSUE TITLE
Wtyczka pobiera za mało danych NMT

### ISSUE THREAD

**Issue by kambe507** [envirosolutionspl/pobieracz_danych_gugik#140]
Dzień dobry, 
próbuję użyć wtyczki do pobrania danych NMT. Z dostępnych skorowidzów wiem, że w obszarze zainteresowań jest wiele zbiorów  o różnej aktualności. W parametrach wtyczki ustawiłam odpowiedni zakres danych (a właściwie nic nie zmieniałam) oraz odznaczyłam "Pobierz tylko aktualne dane" (rozumiejąc, że przez aktualne rozumiemy najświeższe dostępne..., może lepiej by było użyć słowa "najnowsze"). 
Wtyczka pobiera jednak jedynie ostatnie dostępne dane, tj dla przykładu w moim przypadku w układzie KRON86 z 2016 r. a w układzie EVRF2007 dla 2019 r. 

![image](https://github.com/envirosolutionspl/pobieracz_danych_gugik/assets/82141736/78696edc-21c3-455f-9423-2ae193b90b30)

Czy to jest jakiś błąd, czy cos robię nie tak?

**Comment by wojtek19022** [comment]
Dzień dobry, proszę przesłać obszar z którego mają być pobrane dane w formacie SHP lub GPKG na mail: wojciech.solyga@envirosolutions.pl

Przejrzę i zweryfikuję ilość pobranych danych w stosunku do tych co faktycznie zostały pobrane. Taka sytuacja jak zbyt mała ilość pobranych danych nie powinna mieć miejsca

**Comment by kambe507** [comment]
Dzień dobry,
bardzo dziękuję za kontakt.
W nawiązaniu do poniższej korespondencji przesyłam zasięg obszaru dla
którego chciałabym pobrać wszystkie dostępne arkusze NMT. Dla systemu
Kron-86 wykazuje 5 arkuszy podczas gdy powinno ich być 10. Nie mogę też
wybrać formatu ASCII XYZ GRID. ze skorowidzów wiem, że arkuszy w sumie
powinno być 25 - załączam też plik shp.

Pozdrawiam
Kamila Belka

[image: image.png]
