### ISSUE TITLE
 TypeError: __init__() got an unexpected keyword argument 'bladSredniPolozenia' Przy próbie pobierania jakichkolwiek danych

### ISSUE THREAD

**Issue by krak3rs22** [envirosolutionspl/pobieracz_danych_gugik#148]
Hej, jak sobie poradzić z tym problemem, potrzebne mi jest to pod pracę zaliczeniową na studia, pozdrawiam

**Comment by wojtek19022** [comment]
Cześć! Zaktualizuj Pobieracza do najnowszej wersji, ten błąd został naprawiony w wątku #130, #126
