### ISSUE TITLE
Za mała ilość znajdywanych elementów do pobrania

### ISSUE THREAD

**Issue by DogePiesel** [envirosolutionspl/pobieracz_danych_gugik#149]
Witam,
Próbuje pobrać pełen raster wysokości pod mój zbiór danych. Wykorzystując zakładkę NMT -> pobierz z warstwą wektorową, wtyczka proponuje mi pobrać zawsze tylko jeden element, który nie w pełni pokrywa obszar moich danych. Mimo że dane są dostępne i możliwe są do pobrania pojedynczo przez wskazanie punktu na mapie. 
Wersja 1.2.1

**Comment by wojtek19022** [comment]
Dzień dobry, jestem w trakcie zmian tej funkcjonalnościi jak i sposobu działania zakładki "Usługa WMS/Geoportal" dla niektórych produktów :) niedługo będą zrobione zmiany w tej sprawie. Na ten moment można pobrać NMT również przez zakładkę "Usługa WFS", tam jest to lepiej obsłużone
