### ISSUE TITLE
Błąd przy pobieraniu NMT

### ISSUE THREAD

**Issue by GrupekZurek** [envirosolutionspl/pobieracz_danych_gugik#15]
Co najmniej od kilku dni przy okazji pobierania danych NMT/NMPT wyskakuje "błąd Pythona":
TypeError: 'NoneType' object is not iterable

Tymczasem pobieranie ortofotomapy przebiega bez zakłóceń. W przypadku plików .LAS możliwe jest pobieranie poprzez kliknięcie pojedynczego punktu, przy pobieraniu na podstawie zasięgu warstwy wektorowej .shp pojawia się błąd podobny jak w przypadku NMT.

**Comment by aswiader** [comment]
Prawdopodobnie jest to podobny problem, jaki miał miejsce w lutym, kiedy GUGiK zmienił coś w swoich protokołach:
https://github.com/envirosolutionspl/pobieracz_danych_gugik/issues/13
https://www.geoportal.gov.pl/o-geoportalu/aktualnosci/-/asset_publisher/HCHq0YGNRszn/content/09-02-2022-nowe-uslugi-wms-umozliwiajace-pobieranie-danych-wysokosciowych?redirect=%2F&inheritRedirect=true

Będziemy niezmiernie wdzięczni, jeśli i tym razem uda się to naprawić.

**Comment by GrupekZurek** [comment]
Sprawdziłem, pobieranie NMT działa. Dziękuję
