### ISSUE TITLE
Poprawa działania wtyczki dla pobierania duzych danych

### ISSUE THREAD

**Issue by wojtek19022** [envirosolutionspl/pobieracz_danych_gugik#158]
Czasami dla duzych zbiorów (w szczególności kiedy 1 plik waży np. 10GB) QGIS potrafi się wywalić. Możliwe że przez timeout jaki wtedy w nim występuje. Przydałoby się to naprawić, bo nie można wtedy pobrać produktów

**Comment by agluszek** [comment]
to już chyba powinno być ok po naszych ostatnich poprawkach

**Comment by wojtek19022** [comment]
> to już chyba powinno być ok po naszych ostatnich poprawkach

To dodaj tylko odniesienie do PR w którym to robiłaś i zamknę
