### ISSUE TITLE
Dodać możliwość pobierania danych EGIB dla powiatów

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/pobieracz_danych_gugik#16]
Przykładowy link do usługi powiatowej
https://mapy.geoportal.gov.pl/wss/ext/PowiatoweBazyEwidencjiGruntow/0211?service=WFS&request=GetCapabilities

**Comment by ptatar0308** [comment]
Funkcjonalność ta (wersja beta) dodana we wersji 1.0.0. Będzie ona rozwijana i poprawiana na następnych etapach rozwoju wtyczki
