### ISSUE TITLE
W czarnym motywie wtyczka się rozjeżdża

### ISSUE THREAD

**Issue by MateuszPazio** [envirosolutionspl/pobieracz_danych_gugik#164]
Zaobserwowałem, że w czarnym motywie rozjeżdżają się napisy. Zazwyczaj te, które pełnią rolę tytułów.

**Comment by wojtek19022** [comment]
Problemy z ciemnym motywem były już w #52

**Comment by wojtek19022** [comment]
Problem dalej się pojawia, tutaj użytkownik zaobserwował dalej pojawiające rozjeżdżanie się obiektów w UI:  https://github.com/envirosolutionspl/pobieracz_danych_gugik/issues/185#issue-2591436186
