### ISSUE TITLE
Błąd python

### ISSUE THREAD

**Issue by cicholek** [envirosolutionspl/pobieracz_danych_gugik#17]
Od tygodnia nie można pobrać żadnych danych z zakładki WMS/Geoportal. Wyskakuje błąd python. Ponadto nie działa usługa pobierania za pomocą warstw wektorowych. Wyszukuje arkusze kompletnie spoza warstwy.

**Comment by ekolabynet** [comment]
Tak. u mnie jest to samo:
po próbie pobrania NMT wyskakuje bład Pyhtona w QGIS:

             
_2022-05-18T13:05:17     WARNING    Traceback (most recent call last):
              File "/home/piotr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 542, in canvasNmt_clicked
              """Zdarzenie kliknięcia przez wybór NMT/NMPT z mapy"""
              File "/home/piotr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 502, in downloadNmtForSinglePoint
              nmtList = resp[1]
              File "/home/piotr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 509, in filterNmtListAndRunTask
              # print("przed 'set'", len(nmtList))
             TypeError: 'NoneType' object is not iterable_

**Comment by envirosolutionspl** [comment]
> Tak. u mnie jest to samo: po próbie pobrania NMT wyskakuje bład Pyhtona w QGIS:
> 
> _2022-05-18T13:05:17 WARNING Traceback (most recent call last): File "/home/piotr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 542, in canvasNmt_clicked """Zdarzenie kliknięcia przez wybór NMT/NMPT z mapy""" File "/home/piotr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 502, in downloadNmtForSinglePoint nmtList = resp[1] File "/home/piotr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 509, in filterNmtListAndRunTask # print("przed 'set'", len(nmtList)) TypeError: 'NoneType' object is not iterable_

w wersji 0.9.2 błąd nie powinien występować

**Comment by envirosolutionspl** [comment]
zamykam
