### ISSUE TITLE
Błąd pobierania zestawienia zbiorczego ewidencji gruntów i budynków

### ISSUE THREAD

**Issue by Ueschar** [envirosolutionspl/pobieracz_danych_gugik#171]
Jak chcę pobrać "zestawienia zbiorcze ewidencji gruntów i budynków" z kategorii "Inne Dane" dla województwa lub krajowe, to wyskakuję komunikat "Ostrzeżenie: : Nie wskazano obszaru."

**Comment by wojtek19022** [comment]
A to ciekawe, to zajmiesz się tym?
