### ISSUE TITLE
Skalowanie UI

### ISSUE THREAD

**Issue by Rzezimioszek** [envirosolutionspl/pobieracz_danych_gugik#185]
Etykiety z przycisków radio nachodzą na siebie przy zastosowanym motywie "Fusion" w QGIS 3.38.3, w poprzednich wersjach QGIS też tak to wylądało. 

![image](https://github.com/user-attachments/assets/91c6e870-9e74-4dd5-9a11-490e47f54009)

**Comment by wojtek19022** [comment]
Zajmiemy się tym :)

**Comment by wojtek19022** [comment]
Zajmiemy się tym :)

**Comment by wojtek19022** [comment]
Problem pojawił się w #164. Zamknę ten watek i otworzę 164 :)
