### ISSUE TITLE
WFS -BDOO - Brak możliwości pobierania danych w formacie SHP

### ISSUE THREAD

**Issue by karolinaolender** [envirosolutionspl/pobieracz_danych_gugik#21]
Ten format danych jest niedostępny, ,,wyszarzony".

Wersja QGIS 3.22.8
Wersja Wtyczki: 0.9.3

**Comment by karolinaolender** [comment]
Czy można ustawić pobieranie dla poziomu powiatu?

**Comment by ptatar0308** [comment]
Niestety, geoportal nie udostępnia danych BDOO dla poziomu powiatu
