### ISSUE TITLE
WMS - NMT/MNPT - Przy filtracji danych sugeruje się zastosowanie innej formy podania zakresów 

### ISSUE THREAD

**Issue by karolinaolender** [envirosolutionspl/pobieracz_danych_gugik#23]
Wydaje mi się, że obecne są nieintuicyjne i łatwo się pomylić przy wpisywaniu

Wersja QGIS 3.22.8
Wersja Wtyczki: 0.9.3

**Comment by ptatar0308** [comment]
@karolinaolender Proszę o doprecyzowanie :)

**Comment by karolinaolender** [comment]
![image](https://user-images.githubusercontent.com/99646643/188407379-4a8d31e2-7842-4b98-9dc9-911707c1dd60.png)
 Zasugerowałam zmianę 4 ostatnich wierszy na bardziej przyjazne użytkownikowi, np. OD i DO zrobić w jednej linijce. Ponieważ te nazwy są do siebie bardzo zbliżone i łatwo się pomylić :)

**Comment by ptatar0308** [comment]
Do rozpatrzenia w przyszłości
