### ISSUE TITLE
WMS -BDOO - Dane wektorowe pobierają się na lokalny dysk

### ISSUE THREAD

**Issue by karolinaolender** [envirosolutionspl/pobieracz_danych_gugik#28]
-Moim zadaniem to jestem WFS a nie WMS
-Dokładnie taka sama funkcjonalność jest w części WFS

Wersja QGIS 3.22.8
Wersja Wtyczki: 0.9.3

**Comment by ptatar0308** [comment]
Błąd z tej wtyczki został wyeliminowany w najnowszej wersji 1.0
