### ISSUE TITLE
,,Pobierz przez wskazanie punktu na mapie"

### ISSUE THREAD

**Issue by karolinaolender** [envirosolutionspl/pobieracz_danych_gugik#29]
Klikanie ,,Pobierz przez wskazanie punktu na mapie" za każdym razem jak chcemy uzyskać dane.  Może dodać opcję zablokowania celownika? NP dwuklikiem

**Comment by ptatar0308** [comment]
@karolinaolender Prosimy o doprecyzowanie

**Comment by karolinaolender** [comment]
Chodzi o to, że jak pobieram dane dla określonego terenu za pomocą opcji: ,,Pobierz przez wskazanie punktu na mapie" wskazuję miejsce, a następnie jak chce pobrać znów tą opcją to muszę ją kliknąć. Przy pobieraniu danych, np. 10 plików będących obok siebie może to być bardziej czasochłonne. Dlatego zaproponowałam blokowanie tej opcji np. ,,dwuklikiem"

**Comment by ptatar0308** [comment]
Do rozpatrzenia w przyszłości
