### ISSUE TITLE
Usługa WFS - pobieranie warstwą wektorową

### ISSUE THREAD

**Issue by karolinaolender** [envirosolutionspl/pobieracz_danych_gugik#30]
Przy pobieraniu plików warstwą wektorową poligonową, czasem wyskakuje błąd - obszar wyszukiwania jest zbyt duży. Przy tym samym obszarze, ale innej geometrii (linie, punkty) wtyczka działa okej.

![image](https://user-images.githubusercontent.com/99646643/179729454-97d2c935-1780-49f6-9113-14ecc31c4554.png)

Wersja QGIS 3.22.8
Wersja Wtyczki: 0.9.3

**Comment by ptatar0308** [comment]
Usługi WFS z GUGiKu blokują zapytania, które mają na celu pobranie dużej ilości danych. Nie zależy od nas wystąpienie tego komunikatu tylko od odpowiedzi GUGiKu na konkretne URL. Do rozwiązania w przyszłości
