### ISSUE TITLE
Automatyczne dodanie nowopobranej warstwy do mapy

### ISSUE THREAD

**Issue by karolinaolender** [envirosolutionspl/pobieracz_danych_gugik#32]
Pobrane dane zapisują się w folderze wskazanym przez użytkownika. Automatyczne dodanie nowopobranej warstwy do mapy przyśpieszyłoby pracę. Można dać użytkownikowi taką opcję do wyboru.

**Comment by ptatar0308** [comment]
Do rozpatrzenia w przyszłości
