### ISSUE TITLE
Paczka danych / PRNG

### ISSUE THREAD

**Issue by karolinaolender** [envirosolutionspl/pobieracz_danych_gugik#33]
-Wprowadzenie pobierania dla poziomu województwa, powiatu? Dane dla Paczka dla całego kraju jest duża, 
-W wersji 3.22.9 długie pobieranie danych w Formacie SHP – nazwy miejscowości,

**Comment by ptatar0308** [comment]
Na przyciskach zostanie umieszczona informacja dla użytkowników o rozmiarze danych

**Comment by ptatar0308** [comment]
Niestety, nie udostępniono danych dla poziomu powiatów i województw
