### ISSUE TITLE
Brak lub błędy plik rastra

### ISSUE THREAD

**Issue by JarostD1** [envirosolutionspl/pobieracz_danych_gugik#4]
Po pobraniu rastrów QGis przy próbie wczytania rastra ortofotomapy generuje błąd :  
Niepoprawna warstwa: GDAL provider Cannot open GDAL dataset E:\Dane\66582_625414_N-33-103-C-a-3-1.tif: `E:\Dane\66582_625414_N-33-103-C-a-3-1.tif' not recognized as a supported file format. Raster layer Niepoprawny dostawca (dostawca: gdal, URI: E:\Dane\66582_625414_N-33-103-C-a-3-1.tif)
IrfanView generuje komunikat : Nie mogę rozpoznać nagłówka pliku! Nieznany format pliku, uszkodzony plik lib nie istnieje taki plik

**Comment by envirosolutionspl** [comment]
@JarostD1 Najprawdopodobniej ten konkretny plik pobrany z geoportalu jest niepoprawny. Być może plik nie został ściągnięty w całości. Wtyczka nie ma wpływu na jakość pobieranych plików.

**Comment by JarostD1** [comment]
Już wiem o co chodzi, komunikat z Georportalu i w pobranym pliku : **_plik nie istnieje: /ortofotomapa/69758/69758_150818_N-33-103-C-a-3-1.tif_**
Może w wtyczce dobrze było by dać informację, że nie można pobrać pliku, bo brak go pod wskazanym adresem ?
Pozdrawiam

**Comment by JarostD1** [comment]
Komunikat taki jak w poprzednim poście wstępuje w każdym pobranym pliku, a rozmiar pliku to np 65 albo 72 bity

**Comment by envirosolutionspl** [comment]
zostanie to obsłużone w kolejnej wersji

**Comment by envirosolutionspl** [comment]
dodane w wersji 0.3
