### ISSUE TITLE
Błąd pythona przy próbie pobrania EGiB dla powiatu karkonoski

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/pobieracz_danych_gugik#42]
![image](https://user-images.githubusercontent.com/25906739/185869437-36a0b6f4-47c2-4aa1-9325-f2663f475004.png)
![image](https://user-images.githubusercontent.com/25906739/185869635-9dc2aea4-6a20-418c-9a1f-1f70465f6417.png)

**Comment by ptatar0308** [comment]
błąd już nie powinien występować w najnowszej wersji wtyczki 1.0.0
