### ISSUE TITLE
Inne dane - Archiwalne kartoteki osnów - błedy przy pobieraniu

### ISSUE THREAD

**Issue by karolinaolender** [envirosolutionspl/pobieracz_danych_gugik#45]
Wydaje mi się, że po pobraniu pobiera się plik z innego obszaru. Np w okolicach Warszawy na pobranych rysunkach pokazują się takie nazwy miejscowości jak Biskupiec. Ale może mi się tylko wydawac, że to jest źle pobrane ponieważ nie do końca wiem jak powinna wygląda osnowa :)

Wersja wtyczki 1.0
wersja Qgis 3.22.10

**Comment by karolinaolender** [comment]
Teraz pobieranie jest okej, pobrane mapki są dla właściwego obszaru. 
Mam problem z kolei gdy zaznaczam opcję ,,kartotekowe w układzie 1942" - bardzo długo się pobiera albo nie pobiera się wcale.

**Comment by ptatar0308** [comment]
Bardzo długo się pobiera, ponieważ jest to paczka dla bardzo dużego obszaru. Na razie nie mamy możliwości go zmniejszyć :)
