### ISSUE TITLE
Pobieranie BDOO - błędne województwo

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/pobieracz_danych_gugik#61]
Przy próbie pobrania danych BDOO dla województwa mazowieckiego, pobrano dane dla województwa śląskiego
![image](https://github.com/envirosolutionspl/pobieracz_danych_gugik/assets/25906739/18847c38-71eb-49b4-a2c2-fff1d1e89798)

**Comment by wojtek19022** [comment]
Błąd nie występuje w obecnej wersji wtyczki
