### ISSUE TITLE
Wtyczka pobiera dane które według Geoportalu nie istnieją 

### ISSUE THREAD

**Issue by mlecyk2311** [envirosolutionspl/pobieracz_danych_gugik#63]
Pobierając dane NMT dla obszaru dla którego według Geoportalu nie ma wykonanego NMT w układzie NMT PL-EVRF2007-NH, wtyczka je pobrała i zapisała razem ze wszystkimi informacjami sugerującymi datę wykonania i układ.

Przykład pokazano na załączniku, obszary niebieskie są terenami na których zgodnie z Geoportalem wykonane zostało NMT w układzie NMT PL-EVRF2007-NH, pod warstwą NMT takiego kafelka nie ma. 

![Zrzut ekranu 2023-08-18 124809](https://github.com/envirosolutionspl/pobieracz_danych_gugik/assets/142585760/e6d1232c-ae1e-4f57-b757-ff654e8e9bc6)

**Comment by kacpertarka** [comment]
We wskazanym miejscu pobrania jest wykonane NMT w układzie NMT PL-EVRF2007-NH o siatce 5m i jest to zgodne z Geoportalem. Obszary niebieskie wskazują tylko obszary, na których zostało wykonane NMT o siatce 1m.
