### ISSUE TITLE
brak możliwości anulowania procesu pobierania danych

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/pobieracz_danych_gugik#64]
Po kliknięciu na klawisz anulowania w panelu processingu, nie anuluje sie proces pobierania.

![image](https://github.com/envirosolutionspl/pobieracz_danych_gugik/assets/25906739/8c8666e6-7e57-4b75-bb63-6701a09451f4)

**Comment by kacpertarka** [comment]
Poprawa błędu, proszę o sprawdzenie - @envirosolutionspl

**Comment by grucja** [comment]
Działa, ale chyba niepotrzebnie się potem otwiera folder z miejscem gdzie docelowo powinien zapisać się pobrany plik.

**Comment by wojtek19022** [comment]
> Działa, ale chyba niepotrzebnie się potem otwiera folder z miejscem gdzie docelowo powinien zapisać się pobrany plik.

do tego stworzyłem osobny wątek: #84
