### ISSUE TITLE
błąd przy pobieraniu danych warstwą poligonową

### ISSUE THREAD

**Issue by Krzysztof74** [envirosolutionspl/pobieracz_danych_gugik#7]
zrzut ekranu z komunikatem błędu:
![QGIS błąd Pythona](https://user-images.githubusercontent.com/80741874/111266784-4f795700-862b-11eb-920b-7d2cb9a5ceab.png)
szczegóły błędu
![QGIS szczegóły błędu](https://user-images.githubusercontent.com/80741874/111266983-98311000-862b-11eb-828f-0257e6d4ce21.png)

**Comment by envirosolutionspl** [comment]
@Krzysztof74 Proszę o udostępnienie warstwy poligonowej dla której występuje błąd

**Comment by Krzysztof74** [comment]
Proszę bardzo:
[nadl_pol.zip](https://github.com/envirosolutionspl/pobieracz_danych_gugik/files/6147225/nadl_pol.zip)

**Comment by Krzysztof74** [comment]
Dodam tylko, że pobieranie wszystkimi pozostałymi sposobami np. po wskazaniu punktem lub warstwą z małym poligonem działa poprawnie.

**Comment by envirosolutionspl** [comment]
@Krzysztof74 U mnie błąd nie występuje. Proszę sprawdzić czy działa narzędzie `utwórz siatkę` z algorytmów processingu. Jako zasięg proszę podać zasięg z warstwy.
Na jakiej wersji QGIS występuje błąd?
![image](https://user-images.githubusercontent.com/25906739/111279878-7475c600-863b-11eb-85cd-ad9a2710ca52.png)

**Comment by Krzysztof74** [comment]
Narzędzie Utwórz siatkę działa. Sprawdziłem na tworzeniu poligonów o boku 100m dla zasięgu z warstwy.
Obecnie posiadam wersję QGIS 3.4.13 Madera

**Comment by envirosolutionspl** [comment]
Błąd naprawniony. Sugeruję korzystanie z nowszej wersji QGIS, gdzie zoptymalizowane zostały algorytmy processingu. Przykładowo w QGIS 3.4 wyszukiwanie danych za pomocą poligonu trwa 3-4 razy dłużej niż w QGIS 3.16

**Comment by Krzysztof74** [comment]
Nową wersję QGIS-a mam już pobraną ale zainstalowanie jej na komputerze służbowym to nie jest prosta sprawa :)
Odnośnie zgłoszonego błędu to mam rozumieć, że wystarczy przeinstalowanie wtyczki?

**Comment by envirosolutionspl** [comment]
wersja 0.7.2 powinna działać

**Comment by Krzysztof74** [comment]
OK, dziękuję za pomoc.
