### ISSUE TITLE
Brak danych i błąd podczas pobierania nowych danych LAZ 

### ISSUE THREAD

**Issue by Jureq1234** [envirosolutionspl/pobieracz_danych_gugik#70]
Przy próbie pobrania LAZ-u (PL-EVRF2007-NH) według wskazanego punktu na mapie lub poligonu, pojawia się błąd i brak danych.
Dane istnieją ponieważ bezpośrednio można pobrać nowe dane z geoportalu. Gdzieś dwa miesiące temu jeszcze działało.
Przeinstalowałem QGis, zaktualizowałem wtyczkę i sprawdzałem na rożnych komputerach. Nic nie pomaga.
W przypadku starych danych (PL KRON86-NH ) jest ok. 
![image](https://github.com/envirosolutionspl/pobieracz_danych_gugik/assets/88145971/a543140c-b06a-4698-8c7b-2dd79bb1b9c2)
![image](https://github.com/envirosolutionspl/pobieracz_danych_gugik/assets/88145971/3519ca71-004e-48f4-8134-8b8c9b37f5b1)

**Comment by wojtek19022** [comment]
Dobry wieczór, testowaliśmy wtyczkę dla różnych obszarów na terenie kilku województw, na ten moment nie natknęliśmy się na taką sytuację. Proszę o podesłanie nazwy gminy/powiatu, którego tyczy się ta sytuacja

**Comment by SylwiaPi** [comment]
Dzień dobry, nie działa w powiecie wadowickim i oświęcimski  nie można pobrać danych zarówno poprzez wskazanie punktu na mapie lub poligonu, pojawia się błąd i brak danych, a dane są z roku 2023.

**Comment by wojtek19022** [comment]
Dziękuję za tak szybką odpowiedź. Sprawdzimy to jeszcze dzisiaj :)

**Comment by wojtek19022** [comment]
Prawdopodobną diagnozą były problemy po stronie usługi wystawionej przez GUGIK. 
Przetestowałem pobieranie chmur w układzie wysokościowym Kronsztad i EVRF-2007 za pomocą pobierania przez punkt, warstwą wektorową punktową i poligonową i na obu powiatach usługa zwraca pliki z chmurami punktów w formacie LAZ poprawnie.
