### ISSUE TITLE
Update Pobieracza

### ISSUE THREAD

**Issue by wojtek19022** [envirosolutionspl/pobieracz_danych_gugik#77]
Aktualizacja Pobieracza z wersji 1.0.10 na 1.1.0

**Comment by Ueschar** [comment]
Chodzi o graficzną zmianę wersji we wszystkich plikach?

**Comment by wojtek19022** [comment]
Chodzi o podwyższenie wersji z 1.0.10 na 1.1.0 we wszystkich miejscach gdzie jest zapisana wersja 1.0.10
