### ISSUE TITLE
Dane EGIB z błędnymi współrzędnymi

### ISSUE THREAD

**Issue by MateuszPazio** [envirosolutionspl/pobieracz_danych_gugik#90]
Dane dla powiatu kamiennogórskiego, złotoryjskiego i lubański mają nieprawidłowe współrzędne.

**Comment by wojtek19022** [comment]
Nie pobierają się dane EGIB dla powiatu garwolińskiego.

**Comment by wojtek19022** [comment]
co ważne, trzeba sprawdzić, czy to wina wtyczki czy wfs/wms bo niektóre np. wfs mają czasami źle sformatowane dane i są pobierane z odwrotnymi X i Y
