### ISSUE TITLE
Problem z pobraniem danych

### ISSUE THREAD

**Issue by natalia09999** [envirosolutionspl/pobieracz_danych_gugik#91]
Występuje problem z pobraniem danych użytków gruntowych i konturów klasyfikacyjnych dla powiatu sokołowskiego woj. mazowieckie. [EGiB dla powiatu] Co stanowi przyczynę że dane nie są pobierane?

**Comment by wojtek19022** [comment]
Dzień dobry @natalia09999, z tego co widzę, powiat nie udostępnia takich warstw w formie wektorowej na serwisach WFS, proszę jednak napisać do nas na office@envirosolutions.pl. Może będziemy w stanie pomóc :)
